[project]
name = "terraforminator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Igor", email = "igor@zilberman.ca" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "prometheus-client>=0.26.0",
]

[project.scripts]
terraforminator = "terraforminator:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx2>=2.13.1",
    "pytest>=9.1.1",
]
